# Generated by Django 6.0.5 on 2026-07-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
    ]
