# Generated by Django 6.0.5 on 2026-07-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_rename_branch_name_branch_branch_name_transcations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_accounts',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user_accounts',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
