# Generated by Django 6.0.5 on 2026-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0003_alter_user_accounts_current_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='type',
            field=models.CharField(choices=[('transcation', 'TRANSCATION'), ('deposit', 'DEPOSIT'), ('withdraw', 'WITHDRAW')]),
        ),
    ]
