# Generated by Django 6.0.5 on 2026-08-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0004_alter_transcations_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcations',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unique', to='Bank.user_accounts'),
        ),
        migrations.AlterField(
            model_name='transcations',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='odd', to='Bank.user_accounts'),
        ),
    ]
